name: youGotNothingHere
on: 
  issues:
    types: [opened, edited, closed, reopened, labeled, unlabeled, assigned, unassigned]
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: event details
        run: echo "${{ toJSON(github.event)}}"